### ISSUE TITLE
Does Cryptoguard actually check the feasibility of a vulnerable call site? Especially for Android apps

### ISSUE THREAD

**Issue by terry2012** [RigorityJ/rigorityj#20]
Nice project.

Just wonder whether Cryptoguard will trace a vulnerable call site back to an entry function (e.g., onCreate() in Android) to avoid dead code?

**Comment by sazzad114** [comment]
Thanks for your interest in CryptoGuard. Currently, it does not trace it. Maybe in the future, we might consider doing it. In the meantime, if you are interested, contributions are most welcome.
